"""Two summary pages, generated by one Claude API call: a topic summary
across the packet, and a list of candidate Bamboo Weekly topics.

Rendered through render.py, like contents.py, so they inherit the same
typography, page box, and footer. Placed immediately after the contents
page and before the first newsletter - see cli.py.

Degradation is the whole point of this module's shape: no key, no
network, an API error, a malformed response, or a timeout must all mean
"print the packet without the summary pages, report one clear line, carry
on" - never an unhandled traceback on a Friday deadline. build_summary_pages()
therefore never raises; every failure path is folded into its returned
SummaryOutcome.reason.

The API key is never part of Config - only where to find it (see
config.SummaryConfig). read_api_key() reads *only* the requested variable
out of a dotenv-format file that may hold several unrelated keys, and
every error path here is built so the key can never end up in a message
that gets echoed, logged, or written to the run log - see _redact().
"""

import json
import time
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import UTC, date, datetime
from datetime import time as dt_time
from html import escape
from pathlib import Path
from typing import Any

import anthropic
from bs4 import BeautifulSoup

from .config import Config
from .models import Document, Origin, Verdict
from .pdfutil import page_count
from .pipeline import Built
from .render import render

_MAX_OUTPUT_TOKENS = 4096

_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "topics": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "detail": {"type": "string"},
                },
                "required": ["title", "detail"],
                "additionalProperties": False,
            },
        },
        "candidates": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "topic": {"type": "string"},
                    "why": {"type": "string"},
                    "source": {"type": "string"},
                },
                "required": ["topic", "why", "source"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["topics", "candidates"],
    "additionalProperties": False,
}

_TOPICS_ONLY_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {"topics": _SCHEMA["properties"]["topics"]},
    "required": ["topics"],
    "additionalProperties": False,
}


def _schema_for(interest: str) -> dict[str, Any]:
    return _SCHEMA if interest else _TOPICS_ONLY_SCHEMA


_PROMPT_INTRO = """\
You are helping someone prepare their weekly reading packet. Below is the
cleaned text of every newsletter in this week's packet, each preceded by
its publication and subject line.

Produce JSON matching the given schema. This is a quick reading aid
printed on quarter-sheet pages, not a report - each section must fit on
about one small printed page, so be ruthless about length: at most 3
items per list, and each item at most one short sentence per field. Cut
the weakest items rather than shorten every sentence to fit - a list of 2
strong items beats 3 mediocre ones.

1. "topics": the themes that actually recur across this week's
   newsletters - not a list of subjects (a contents page already lists
   those), but what connects them. Each item is a short phrase ("title")
   plus one sentence ("detail") saying what the connection actually is.
   If nothing genuinely recurs, return an empty list rather than
   inventing a connection.
"""

_PROMPT_INTEREST = """\
2. "candidates": things in this week's newsletters worth following up,
   judged against what this reader says they are looking for:

{interest}

   For each, one sentence each: the thing itself ("topic"), why it is
   worth their time ("why"), and where they would go next ("source") -
   name something specific, not a category in the abstract.
"""

_PROMPT_CLOSE = """\
Be honest rather than exhaustive: if you have nothing good to offer for a
list, return an empty list rather than padding it with weak ideas. A
short, honest list beats five weak ones - and a list that fits the page
beats one that doesn't.

--- NEWSLETTERS ---
"""


def _prompt_header(interest: str) -> str:
    if not interest:
        return _PROMPT_INTRO + "\n" + _PROMPT_CLOSE
    indented = "\n".join(f"   {line}" for line in interest.splitlines())
    return (
        _PROMPT_INTRO
        + "\n"
        + _PROMPT_INTEREST.format(interest=indented)
        + "\n"
        + _PROMPT_CLOSE
    )


class SummaryError(Exception):
    """The summary could not be produced - always caught by
    build_summary_pages() and turned into a degraded SummaryOutcome,
    never allowed to escape and abort a run."""


@dataclass(frozen=True, slots=True)
class Topic:
    title: str
    detail: str


@dataclass(frozen=True, slots=True)
class Candidate:
    topic: str
    why: str
    source: str


@dataclass(frozen=True, slots=True)
class SummaryContent:
    topics: tuple[Topic, ...]
    candidates: tuple[Candidate, ...]


@dataclass(frozen=True, slots=True)
class ApiResponse:
    """What a Caller returns: just enough to render the pages and report
    cost - never the raw SDK response object, so a fake caller in a test
    never needs to impersonate the whole anthropic.types.Message shape."""

    text: str
    input_tokens: int | None
    output_tokens: int | None


Caller = Callable[[str, str, str, float, dict[str, Any]], ApiResponse]


@dataclass(frozen=True, slots=True)
class SummaryOutcome:
    pages: tuple[Built, ...]
    reason: str | None
    elapsed_seconds: float
    input_tokens: int | None
    output_tokens: int | None


def _redact(message: str, secret: str) -> str:
    """Remove every occurrence of `secret` from `message`.

    Guards the empty-secret case explicitly: str.replace("", "x") would
    otherwise splice "x" between every character of the message, which is
    exactly the shape of bug this function exists to prevent - not cause.
    """
    if not secret:
        return message
    return message.replace(secret, "<redacted>")


def read_api_key(path: Path, var_name: str) -> str:
    """Read one variable out of a dotenv-format file.

    Simple `NAME=value` parsing only: blank lines and lines starting with
    "#" are skipped, and a value wrapped in matching quotes has them
    stripped. Only the requested variable is ever inspected - the file
    may hold several unrelated keys, and nothing else in it is read,
    named, or reported on any path through this function.
    """
    try:
        text = path.read_text()
    except FileNotFoundError as error:
        raise SummaryError(f"no API key: {path} does not exist") from error
    except OSError as error:
        raise SummaryError(f"no API key: could not read {path}: {error}") from error

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name, _, value = stripped.partition("=")
        if name.strip() != var_name:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if not value:
            raise SummaryError(f"no API key: {var_name} in {path} is empty")
        return value
    raise SummaryError(f"no API key: {path} does not define {var_name}")


def _document_text(document: Document) -> str:
    return BeautifulSoup(document.html, "lxml").get_text("\n", strip=True)


def _build_prompt(built: Sequence[Built], interest: str) -> str:
    sections = [
        f"## {item.document.publication} — {item.document.title}\n\n"
        f"{_document_text(item.document)}"
        for item in built
    ]
    return _prompt_header(interest) + "\n\n".join(sections)


def _parse_content(text: str, interest: str) -> SummaryContent:
    try:
        data = json.loads(text)
    except json.JSONDecodeError as error:
        raise SummaryError(f"malformed response: not valid JSON ({error})") from error
    if not isinstance(data, dict):
        raise SummaryError("malformed response: expected a JSON object")
    try:
        topics = tuple(
            Topic(title=str(item["title"]), detail=str(item["detail"]))
            for item in data["topics"]
        )
        # Only asked for when the reader described an interest, so only
        # required back then - a model answering the topics-only schema
        # has no "candidates" key to read.
        candidates = (
            tuple(
                Candidate(
                    topic=str(item["topic"]),
                    why=str(item["why"]),
                    source=str(item["source"]),
                )
                for item in data["candidates"]
            )
            if interest
            else ()
        )
    except (KeyError, TypeError) as error:
        raise SummaryError(f"malformed response: {error}") from error
    return SummaryContent(topics=topics, candidates=candidates)


def _default_caller(
    api_key: str,
    model: str,
    prompt: str,
    timeout: float,
    schema: dict[str, Any],
) -> ApiResponse:
    """Call the live API, streamed.

    Streamed rather than a single blocking .create(): the packet's text
    runs to roughly 40k input tokens, and a non-streaming call over that
    much input sat idle - no bytes at all - for the model's own thinking
    time before answering, which is exactly what tripped the client-side
    read timeout in the first live run of this feature (a 60s timeout,
    once). The API sends periodic events during a long streamed turn that
    a plain .create() never gets, so streaming is what actually fixed it,
    not just a bigger timeout number. effort is "medium": this is
    extraction over already-cleaned text, not a hard reasoning problem,
    so the full "high" default cost and latency buys nothing here.
    """
    client = anthropic.Anthropic(api_key=api_key, max_retries=1).with_options(
        timeout=timeout
    )
    with client.messages.stream(
        model=model,
        max_tokens=_MAX_OUTPUT_TOKENS,
        messages=[{"role": "user", "content": prompt}],
        output_config={
            "format": {"type": "json_schema", "schema": schema},
            "effort": "medium",
        },
    ) as stream:
        response = stream.get_final_message()
    if getattr(response, "stop_reason", None) == "refusal":
        raise SummaryError("the model declined to answer")
    # Not content[0]: Opus 5 thinks by default, so a ThinkingBlock precedes
    # the TextBlock in a real response - a live run against the actual
    # queue hit exactly this ('ThinkingBlock' object has no attribute
    # 'text') before this search replaced the blind index.
    try:
        text = next(block.text for block in response.content if block.type == "text")
    except StopIteration as error:
        raise SummaryError("response had no text content") from error
    usage = getattr(response, "usage", None)
    return ApiResponse(
        text=text,
        input_tokens=getattr(usage, "input_tokens", None) if usage else None,
        output_tokens=getattr(usage, "output_tokens", None) if usage else None,
    )


def _topics_document(topics: Sequence[Topic], packet_date: date) -> Document:
    rows = "".join(
        f"<li><strong>{escape(topic.title)}</strong> — {escape(topic.detail)}</li>"
        for topic in topics
    )
    return Document(
        origin=Origin(kind="url", identifier="summary-topics"),
        publication="Summary",
        title="This Week's Topics",
        date=datetime.combine(packet_date, dt_time.min, tzinfo=UTC),
        html=f"<ul>{rows}</ul>",
    )


def _candidates_document(
    candidates: Sequence[Candidate], packet_date: date, title: str
) -> Document:
    rows = "".join(
        f"<li><strong>{escape(candidate.topic)}</strong> — "
        f"{escape(candidate.why)} <em>Source: {escape(candidate.source)}</em></li>"
        for candidate in candidates
    )
    return Document(
        origin=Origin(kind="url", identifier="summary-candidates"),
        publication="Summary",
        title=title,
        date=datetime.combine(packet_date, dt_time.min, tzinfo=UTC),
        html=f"<ul>{rows}</ul>",
    )


def _render_pages(
    content: SummaryContent,
    config: Config,
    packet_date: date,
    out_dir: Path,
    render_fn: Callable[..., Path],
) -> list[Built]:
    pages: list[Built] = []
    if content.topics:
        document = _topics_document(content.topics, packet_date)
        pdf = render_fn(document, config, out_dir=out_dir / "topics")
        pages.append(
            Built(
                document=document, pdf=pdf, cells=page_count(pdf), verdict=Verdict.FULL
            )
        )
    if content.candidates:
        document = _candidates_document(
            content.candidates,
            packet_date,
            config.summary.personal.title if config.summary.personal else "",
        )
        pdf = render_fn(document, config, out_dir=out_dir / "candidates")
        pages.append(
            Built(
                document=document, pdf=pdf, cells=page_count(pdf), verdict=Verdict.FULL
            )
        )
    return pages


def build_summary_pages(
    built: Sequence[Built],
    config: Config,
    packet_date: date,
    out_dir: Path,
    render_fn: Callable[..., Path] = render,
    caller: Caller = _default_caller,
) -> SummaryOutcome:
    """Attempt the one API call and render its two pages. Never raises:
    any failure - no key, no network, an API error, a malformed response,
    a timeout - degrades to SummaryOutcome(pages=(), reason=<one line>).

    An empty topics or candidates list from a *successful* call is not a
    failure - the model saying it has nothing good to add is the honest
    outcome the prompt asks for, so that page is simply omitted and
    `reason` stays None.
    """
    start = time.monotonic()
    api_key = ""
    try:
        api_key = read_api_key(config.summary.api_key_file, config.summary.api_key_var)
        personal = config.summary.personal
        interest = personal.looking_for if personal else ""
        prompt = _build_prompt(built, interest)
        response = caller(
            api_key,
            config.summary.model,
            prompt,
            config.summary.timeout_seconds,
            _schema_for(interest),
        )
        content = _parse_content(response.text, interest)
        pages = _render_pages(content, config, packet_date, out_dir, render_fn)
        return SummaryOutcome(
            pages=tuple(pages),
            reason=None,
            elapsed_seconds=time.monotonic() - start,
            input_tokens=response.input_tokens,
            output_tokens=response.output_tokens,
        )
    except Exception as error:  # noqa: BLE001 - degrade, never abort a Friday print run
        reason = _redact(str(error), api_key)
        return SummaryOutcome(
            pages=(),
            reason=reason,
            elapsed_seconds=time.monotonic() - start,
            input_tokens=None,
            output_tokens=None,
        )
